# Generated by Django 4.2 on 2023-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuser',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
