# Generated by Django 4.2 on 2023-05-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodels',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
